environment:
  CYG_ROOT: C:\cygwin
  CYG_BASH: C:\cygwin\bin\bash
  CYG_CACHE: C:\cygwin\var\cache\setup
  CYG_EXE: C:\cygwin\setup-x86.exe
  CYG_MIRROR: http://cygwin.mirror.constant.com
  SCI_RUN: /cygdrive/c/SMALLTALKCI-master/run.sh

  matrix:
    - SMALLTALK: Pharo-6.1
      SMALLTALK_CONFIG: .smalltalk.Unit.ston
    - SMALLTALK: Pharo-5.0
      SMALLTALK_CONFIG: .smalltalk.Unit.ston
    - SMALLTALK: Pharo-6.1
      SMALLTALK_CONFIG: .smalltalk.Integration.ston
    - SMALLTALK: Pharo-5.0
      SMALLTALK_CONFIG: .smalltalk.Integration.ston

cache:
  - '%CYG_CACHE%'
  - 'c:\miktex'

platform:
  - x86

# MiKTeX installation inspired from https://github.com/open62541/open62541/blob/master/appveyor.yml
install:
  - '%CYG_EXE% -dgnqNO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P unzip'
  - ps: Start-FileDownload "https://github.com/hpi-swa/SMALLTALKCI/archive/master.zip" "C:\SMALLTALKCI.zip"
  - 7z x C:\SMALLTALKCI.zip -oC:\ -y > NULL
  # Install miktex to get pdflatex, if we don't get it from the cache
  - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe appveyor DownloadFile http://mirrors.ctan.org/systems/win32/miktex/setup/miktex-portable.exe
  - if not exist c:\miktex\texmfs\install\miktex\bin\pdflatex.exe 7z x miktex-portable.exe -oc:\miktex >NUL
  # Remove some big files to reduce size to be cached
  - if exist c:\miktex\texmfs\install\doc rd /s /q c:\miktex\texmfs\install\doc
  - if exist c:\miktex\texmfs\install\internal rd /s /q c:\miktex\texmfs\install\internal
  - if exist c:\miktex\texmfs\install\miktex\bin\biber.exe rd /s /q c:\miktex\texmfs\install\miktex\bin\biber.exe
  - if exist c:\miktex\texmfs\install\miktex\bin\icudt58.dll rd /s /q c:\miktex\texmfs\install\miktex\bin\icudt58.dll
  - if exist c:\miktex\texmfs\install\miktex\bin\a5toa4.exe rd /s /q c:\miktex\texmfs\install\miktex\bin\a5toa4.exe
  - set "PATH=%PATH%;c:\miktex\texmfs\install\miktex\bin"
  - mpm --update-some=scripts/ci/latex-dependencies.txt

build: false

test_script:
  - '%CYG_BASH% -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; $SCI_RUN $SMALLTALK_CONFIG"'
  # do not cache log
  - rd /s /q c:\miktex\texmfs\data\miktex\log