name: integration.app

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev-8 branch
  push:
    branches: [ dev-8 ]
  pull_request:
    branches: [ dev-8 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-version: Pharo64-8.0
          smalltalk-build-dir: ${SMALLTALK_CI_BUILD}
      - name: go
        shell: bash
        timeout-minutes: 15
        run: |
          env
          cp -r archetypes ${{ steps.smalltalkci.outputs.smalltalk-build-dir }}
          mkdir -p ${{ steps.smalltalkci.outputs.smalltalk-build-dir }}
          smalltalkci -s  ${{ steps.smalltalkci.outputs.smalltalk-version }} .smalltalk.Integration.App.ston
