name: system

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PATH: "$HOME/texlive/bin/x86_64-linux:$HOME/texlive/bin/x86_64-darwin:$HOME/pillar/build:$PATH"

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev-8 branch
  push:
    branches: [ dev-8 ]
  pull_request:
    branches: [ dev-8 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest ]
        archetype: [book, presentation, welcome, basic-latex]
        output: [html, pdf]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
        with:  
          fetch-depth: 0
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-version: Pharo64-8.0
      - run: scripts/system-tests/testarchetype.sh  ${{ matrix.archetype }} ${{ matrix.output }}
        shell: bash
        timeout-minutes: 15
