name: unit.app

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev-8 branch
  push:
    branches: [ dev-8 ]
  pull_request:
    branches: [ dev-8 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-image: Pharo64-9.0
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-image }} .smalltalk.Unit.App.ston
        shell: bash
        timeout-minutes: 15
